version: '3.8'
services:
  openresty:
    hostname: openresty
    container_name: openresty
    build: ./openresty
    image: gravity/openresty
    restart: unless-stopped
    # depends_on:
    #   - hasura
    volumes:
      - /tmp
      - openresty-cert:/etc/nginx/cert
    tmpfs:
      - /var/run/openresty
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
      - backend
    environment:
      - WORKERS
      - RESOLVER
      - SERVER_NAME
      - ERROR_LOG_LEVEL
      - WORKER_CONNECTIONS
      - CLIENT_MAX_BODY_SIZE
      - CLIENT_BODY_BUFFER_SIZE
      - LUA_SOCKET_POOL_SIZE
      - LUA_CODE_CACHE
      - CERT_CACHE_SIZE
      - ACME_EMAIL
      - JWT_EXPIRES_IN
      - JWT_PUBLIC_PEM
      - JWT_PRIVATE_PEM
      - HASURA_LOCATION_OVERRIDE
      - HASURA_GRAPHQL_ADMIN_SECRET
    command: /bin/ash -c "resty -l app.build_config > /var/run/openresty/nginx.conf && openresty -c /var/run/openresty/nginx.conf"
    logging:
      driver: journald

  hasura:
    hostname: hasura
    container_name: hasura
    image: hasura/graphql-engine
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - backend
    environment:
      - HASURA_GRAPHQL_DEV_MODE
      - HASURA_GRAPHQL_ADMIN_SECRET
      - HASURA_GRAPHQL_ENABLE_CONSOLE
      - 'HASURA_GRAPHQL_ENABLE_TELEMETRY=false'
      - 'HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres'
      - 'HASURA_GRAPHQL_JWT_SECRET={"type":"Ed25519", "key":"${JWT_PUBLIC_PEM}", "claims_map": {"x-hasura-allowed-roles": ["user", "admin"], "x-hasura-default-role": "user", "x-hasura-user-id": {"path": "$$.sub"}}}'
    logging:
      driver: journald

  postgres:
    hostname: postgres
    container_name: postgres
    image: postgis/postgis
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD
    logging:
      driver: journald

volumes:
  openresty-cert:

networks:
  proxy:
  backend:
    internal: true
