version: '3.8'
services:
  openresty:
    volumes:
      - ./openresty/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./openresty/app:/usr/local/openresty/site/lualib/app
      - ./openresty/test:/usr/local/openresty/site/lualib/test
    environment:
      - "WORKERS=2"
      - "IS_PROD=false"
      - "LUA_CODE_CACHE=off"
      - "ERROR_LOG_LEVEL=debug"

  hasura:
    environment:
      - "HASURA_GRAPHQL_DEV_MODE=true"
      - "HASURA_GRAPHQL_LOG_LEVEL=debug"
      - "HASURA_GRAPHQL_ENABLE_CONSOLE=true"
      - "HASURA_GRAPHQL_ENABLE_METADATA_QUERY_LOGGING=true"
