version: '3.8'
services:
  caddy:
    container_name: caddy
    image: caddy/caddy
    restart: unless-stopped
    depends_on:
      - hasura
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - backend
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_config:/config
      - caddy_data:/data
      # - ./images:/srv
    environment:
      - CADDY_SERVER_NAME
    logging:
      driver: journald

  hasura:
    container_name: hasura
    image: hasura/graphql-engine
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - backend
    environment:
      - HASURA_GRAPHQL_DEV_MODE
      - HASURA_GRAPHQL_ADMIN_SECRET
      - HASURA_GRAPHQL_ENABLE_CONSOLE
      - HASURA_GRAPHQL_ENABLE_TELEMETRY=false
      - HASURA_GRAPHQL_AUTH_HOOK=http://openresty/auth/hasura
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    logging:
      driver: journald

  postgres:
    container_name: postgres
    image: postgis/postgis
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD
    logging:
      driver: journald

volumes:
  caddy_data:
    # external: true
  caddy_config:

  backend:
    internal: true
