name: tentura

services:
  openresty:
    hostname: openresty
    container_name: openresty
    image: vbulavintsev/openresty-tentura:${OPENRESTY_VERSION:-latest}
    restart: unless-stopped
    depends_on:
       - hasura
    volumes:
      - /tmp
      - ./images:/srv/images
      - ./static:/usr/local/openresty/nginx/html:ro
      - openresty-cert:/etc/nginx/cert
    tmpfs:
      - /var/run/openresty
    ports:
      - 80:80/tcp
      - 443:443/tcp
    networks:
      - proxy
      - backend
    environment:
      - WORKERS
      - RESOLVER
      - SERVER_NAME
      - ERROR_LOG_LEVEL
      - WORKER_CONNECTIONS
      - CLIENT_MAX_BODY_SIZE
      - CLIENT_BODY_BUFFER_SIZE
      - LUA_SOCKET_POOL_SIZE
      - LUA_CODE_CACHE
      - CERT_CACHE_SIZE
      - ACME_EMAIL
      - JWT_EXPIRES_IN
      - JWT_PUBLIC_PEM
      - JWT_PRIVATE_PEM
      - WITH_TEST_LOCATION
      - HASURA_LOCATION_OVERRIDE
      - HASURA_GRAPHQL_ADMIN_SECRET
      - 'HASURA_URL=http://hasura:8080/v1/graphql'
    logging:
      driver: journald

  hasura:
    hostname: hasura
    container_name: hasura
    image: hasura/graphql-engine:${HASURA_VERSION:-latest}
    restart: unless-stopped
    read_only: true
    depends_on:
      - postgres
    networks:
      - backend
    environment:
      - HASURA_GRAPHQL_DEV_MODE
      - HASURA_GRAPHQL_ADMIN_SECRET
      - HASURA_GRAPHQL_ENABLE_CONSOLE
      - 'HASURA_GRAPHQL_ENABLE_TELEMETRY=false'
      - 'HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS=false'
      - 'HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres'
      - 'HASURA_GRAPHQL_JWT_SECRET={"type":"Ed25519", "key":"${JWT_PUBLIC_PEM}", "claims_map": {"x-hasura-allowed-roles": ["user", "admin"], "x-hasura-default-role": "user", "x-hasura-user-id": {"path": "$$.sub"}}}'
    logging:
      driver: journald

  postgres:
    hostname: postgres
    container_name: postgres
    image: vbulavintsev/postgres-tentura:${POSTGRES_VERSION:-latest}
    restart: unless-stopped
    depends_on:
      - meritrank-service
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD
      - 'MERITRANK_SERVICE_URL=tcp://meritrank-service:10234'
    logging:
      driver: journald

  meritrank-service:
    hostname: meritrank-service
    container_name: meritrank-service
    image: vbulavintsev/meritrank-service:${MERITRANK_VERSION:-latest}
    restart: unless-stopped
    read_only: true
    networks:
      - backend
    environment:
      - MERITRANK_NUM_WALK
      - MERITRANK_TOP_NODES_LIMIT
      - MERITRANK_SERVICE_THREADS
      - 'MERITRANK_SERVICE_URL=tcp://0.0.0.0:10234'
    logging:
      driver: journald

volumes:
  openresty-cert:

networks:
  proxy:
  backend:
    internal: true
